# -*- coding: utf-8 -*-
"""simple chat bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FDnoA3FqzyWY3NqVGgV2aNxK8LC6rAJN
"""

!pip install accelerate

!pip install pymongo

!pip install rasa pymongo

import pymongo

# Connect to MongoDB
client = pymongo.MongoClient("mongodb+srv://lanaweiss02:whatever.ittakes@cluster0.loap7.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0")
db = client["purchase_history"]
collection = db["purchase"]

# Fetch the data
data = list(collection.find())

!apt install python3.10-venv

!python3 -m venv myenv
!source myenv/bin/activate
!pip install <pandas>

!pip install --upgrade setuptools

!apt install python3.10-venv
!python3.10 -m venv myenv
!source myenv/bin/activate

!pip cache purge

!pip install wheel
!pip install rasa-x --extra-index-url https://pypi.rasa.com/simple --use-feature=in-tree-build

!pip install importlib-resources

!pip install importlib-metadata

!rasa x

import os
os.environ['SQLALCHEMY_SILENCE_UBER_WARNING'] = '1'

!pip install --upgrade rasa

!rasa train --config config.yml --data /content/nlu.yml /content/stories.yml --domain /content/domain.yml

!rasa run actions --port 5055

action_endpoint = {
    "url": "http://localhost:5055/webhook"
}

import pkg_resources

import sys
sys.path.append("/content/actions.py")

!rasa shell --endpoints endpoints.yml --model models/20241016-175331-weary-render.tar.gz